server:
  port: 8082

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5433/catalog_db
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
