server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/users_db
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000 # 15 mins (15 * 60 * 1000)
      refresh-token:
        expiration: 604800000 # 7 days