server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5435/inventory_db
    username: app
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
